In [1]:
# importações
import pandas as pd
import requests

In [2]:
# Localização (São Paulo) - Teste inicial
latitude = -23.5505
longitude = -46.6333

# Intervalo de datas
start_date = "20240101"
end_date = "20241231"

# Variáveis climáticas
parameters = [
    "PRECTOTCORR",        # Precipitação
    "T2M",                # Temperatura média
    "RH2M",               # Umidade relativa
    "WS2M",               # Velocidade do vento
    "ALLSKY_SFC_SW_DWN"   # Radiação solar
]

parameters_str = ",".join(parameters)

In [3]:
url = (
    "https://power.larc.nasa.gov/api/temporal/daily/point"
    f"?parameters={parameters_str}"
    "&community=AG"
    f"&longitude={longitude}"
    f"&latitude={latitude}"
    f"&start={start_date}"
    f"&end={end_date}"
    "&format=JSON"
)

print("URL utilizada:")
print(url)

response = requests.get(url)

print("\nStatus da requisição:")
print(response.status_code)

URL utilizada:
https://power.larc.nasa.gov/api/temporal/daily/point?parameters=PRECTOTCORR,T2M,RH2M,WS2M,ALLSKY_SFC_SW_DWN&community=AG&longitude=-46.6333&latitude=-23.5505&start=20240101&end=20241231&format=JSON

Status da requisição:
200

In [5]:
# Transformando em Dataframe para consulta

data = response.json()

parameters_data = data["properties"]["parameter"]

df = pd.DataFrame(parameters_data)

df.index = pd.to_datetime(df.index)

df = df.reset_index()

df.rename(columns={"index": "date"}, inplace=True)

df.head()

        date  PRECTOTCORR    T2M   RH2M  WS2M  ALLSKY_SFC_SW_DWN
0 2024-01-01         0.06  23.15  69.16  2.99              16.71
1 2024-01-02         0.37  23.99  69.60  2.16              20.61
2 2024-01-03         4.72  24.20  75.18  2.47              16.73
3 2024-01-04         4.64  23.63  77.13  3.15              16.95
4 2024-01-05         2.36  23.16  75.31  2.68              21.71

In [6]:
# Validando os valores
print("Informações gerais:")
display(df.info())

print("\nValores nulos:")
display(df.isnull().sum())

print("\nEstatísticas:")
display(df.describe())

Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               366 non-null    datetime64[ns]
 1   PRECTOTCORR        366 non-null    float64
 2   T2M                366 non-null    float64
 3   RH2M               366 non-null    float64
 4   WS2M               366 non-null    float64
 5   ALLSKY_SFC_SW_DWN  366 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 17.3 KB

None

Valores nulos:

date                 0
PRECTOTCORR          0
T2M                  0
RH2M                 0
WS2M                 0
ALLSKY_SFC_SW_DWN    0
dtype: int64

Estatísticas:

,date,PRECTOTCORR,T2M,RH2M,WS2M,ALLSKY_SFC_SW_DWN
count,366,366.000000,366.000000,366.000000,366.000000,366.000000
mean,2024-07-01 12:00:00.000000256,2.736120,21.516639,71.147131,2.298306,16.328251
min,2024-01-01 00:00:00,0.000000,10.230000,28.640000,0.830000,1.670000
25%,2024-04-01 06:00:00,0.030000,19.422500,63.820000,1.610000,12.962500
50%,2024-07-01 12:00:00,0.275000,22.190000,73.950000,2.140000,16.625000
75%,2024-09-30 18:00:00,3.067500,23.812500,81.057500,2.800000,20.305000
max,2024-12-31 00:00:00,39.170000,28.050000,93.140000,4.990000,29.240000
std,NaN,5.395045,3.259038,12.620045,0.840585,5.485059

In [7]:
df.to_csv(
    "nasa_power_sao_paulo_2024.csv",
    index=False
)